import { Property, LocalInfo, Template } from '../types';

const defaultPDFSections = [
  {
    id: 'header',
    type: 'header' as const,
    title: 'Property Header',
    enabled: true,
    order: 1,
    content: 'Welcome to {{propertyName}}',
    styling: {
      fontSize: 32,
      fontWeight: 'bold' as const,
      color: '#FFFFFF',
      padding: 20,
      marginTop: 0,
      marginBottom: 20
    }
  },
  {
    id: 'property-info',
    type: 'property-info' as const,
    title: 'Property Description',
    enabled: true,
    order: 2,
    content: 'Welcome to Your Stay',
    styling: {
      fontSize: 24,
      fontWeight: 'bold' as const,
      color: '#333333',
      padding: 15,
      marginTop: 0,
      marginBottom: 15,
      borderLeft: { width: 4, color: '#3B82F6' }
    }
  },
  {
    id: 'checkin',
    type: 'checkin' as const,
    title: 'Check-in Instructions',
    enabled: true,
    order: 3,
    content: 'Check-in Instructions',
    styling: {
      fontSize: 20,
      fontWeight: 'bold' as const,
      color: '#333333',
      padding: 15,
      marginTop: 0,
      marginBottom: 15,
      borderLeft: { width: 4, color: '#3B82F6' }
    }
  },
  {
    id: 'wifi',
    type: 'wifi' as const,
    title: 'WiFi Information',
    enabled: true,
    order: 4,
    content: 'WiFi Information',
    styling: {
      fontSize: 18,
      fontWeight: 'bold' as const,
      color: '#3B82F6',
      backgroundColor: '#3B82F615',
      padding: 20,
      marginTop: 0,
      marginBottom: 20
    }
  },
  {
    id: 'rules',
    type: 'rules' as const,
    title: 'House Rules',
    enabled: true,
    order: 5,
    content: 'House Rules',
    styling: {
      fontSize: 20,
      fontWeight: 'bold' as const,
      color: '#333333',
      padding: 15,
      marginTop: 0,
      marginBottom: 15,
      borderLeft: { width: 4, color: '#3B82F6' }
    }
  },
  {
    id: 'local-info',
    type: 'local-info' as const,
    title: 'Local Information & Recommendations',
    enabled: true,
    order: 6,
    content: 'Local Information & Recommendations',
    styling: {
      fontSize: 20,
      fontWeight: 'bold' as const,
      color: '#333333',
      padding: 15,
      marginTop: 0,
      marginBottom: 20,
      borderLeft: { width: 4, color: '#3B82F6' }
    }
  },
  {
    id: 'emergency',
    type: 'emergency' as const,
    title: 'Emergency Contacts',
    enabled: true,
    order: 7,
    content: 'Emergency Contacts',
    styling: {
      fontSize: 18,
      fontWeight: 'bold' as const,
      color: '#856404',
      backgroundColor: '#fff3cd',
      padding: 20,
      marginTop: 0,
      marginBottom: 30
    }
  },
  {
    id: 'footer',
    type: 'footer' as const,
    title: 'Footer',
    enabled: true,
    order: 8,
    content: 'Generated by RentalBook Platform',
    styling: {
      fontSize: 12,
      fontWeight: 'normal' as const,
      color: '#666666',
      padding: 20,
      marginTop: 20,
      marginBottom: 0
    }
  }
];

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    ownerId: 'user-1',
    name: 'Seaside Villa',
    address: '123 Ocean View Drive',
    city: 'Santa Monica',
    country: 'USA',
    description: 'Beautiful villa with ocean views',
    checkInInstructions: 'Key is in the lockbox, code: 1234',
    wifiPassword: 'oceanview123',
    houseRules: 'No smoking, no pets',
    emergencyContacts: 'Police: 911, Fire: 911',
    templateId: 'modern-blue',
    isPublished: true,
    websiteUrl: 'https://seaside-villa.example.com',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20')
  }
];

export const mockLocalInfo: LocalInfo[] = [
  {
    id: 'local-1',
    name: 'City General Hospital',
    category: 'hospital',
    address: '456 Medical Center Blvd',
    phone: '+1-555-0123',
    description: '24/7 emergency services',
    city: 'Santa Monica',
    country: 'USA',
    verified: true,
    openingHours: '24/7'
  },
  {
    id: 'local-2',
    name: "Joe's Pharmacy",
    category: 'pharmacy',
    address: '789 Main Street',
    phone: '+1-555-0456',
    description: 'Full-service pharmacy with prescription services',
    city: 'Santa Monica',
    country: 'USA',
    verified: true,
    openingHours: '8:00 AM - 10:00 PM'
  },
  {
    id: 'local-3',
    name: 'Ocean Breeze Restaurant',
    category: 'restaurant',
    address: '321 Seaside Avenue',
    phone: '+1-555-0789',
    website: 'https://oceanbreeze.com',
    description: 'Fresh seafood with ocean views',
    city: 'Santa Monica',
    country: 'USA',
    verified: true,
    rating: 4.5,
    openingHours: '11:00 AM - 11:00 PM'
  }
];

export const templates: Template[] = [
  {
    id: 'modern-blue',
    name: 'Modern Blue',
    category: 'modern',
    preview: '/templates/modern-blue.jpg',
    colors: { primary: '#3B82F6', secondary: '#1E40AF', accent: '#60A5FA' },
    pdfTemplate: {
      id: 'pdf-modern-blue',
      name: 'Modern Blue PDF',
      layout: {
        pageSize: 'a4',
        orientation: 'portrait',
        margins: { top: 40, right: 40, bottom: 40, left: 40 },
        columns: 1
      },
      sections: defaultPDFSections,
      styling: {
        fontFamily: 'Arial, sans-serif',
        primaryColor: '#3B82F6',
        secondaryColor: '#1E40AF',
        accentColor: '#60A5FA',
        backgroundColor: '#ffffff',
        headerGradient: true,
        roundedCorners: true,
        shadows: true
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  },
  {
    id: 'classic-green',
    name: 'Classic Green',
    category: 'classic',
    preview: '/templates/classic-green.jpg',
    colors: { primary: '#059669', secondary: '#047857', accent: '#34D399' },
    pdfTemplate: {
      id: 'pdf-classic-green',
      name: 'Classic Green PDF',
      layout: {
        pageSize: 'a4',
        orientation: 'portrait',
        margins: { top: 40, right: 40, bottom: 40, left: 40 },
        columns: 1
      },
      sections: defaultPDFSections.map(section => ({
        ...section,
        styling: {
          ...section.styling,
          color: section.styling.color === '#3B82F6' ? '#059669' : section.styling.color,
          backgroundColor: section.styling.backgroundColor?.replace('#3B82F6', '#059669'),
          borderLeft: section.styling.borderLeft ? { ...section.styling.borderLeft, color: '#059669' } : undefined
        }
      })),
      styling: {
        fontFamily: 'Arial, sans-serif',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        accentColor: '#34D399',
        backgroundColor: '#ffffff',
        headerGradient: true,
        roundedCorners: false,
        shadows: false
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  },
  {
    id: 'minimal-gray',
    name: 'Minimal Gray',
    category: 'minimal',
    preview: '/templates/minimal-gray.jpg',
    colors: { primary: '#6B7280', secondary: '#374151', accent: '#9CA3AF' },
    pdfTemplate: {
      id: 'pdf-minimal-gray',
      name: 'Minimal Gray PDF',
      layout: {
        pageSize: 'a4',
        orientation: 'portrait',
        margins: { top: 30, right: 30, bottom: 30, left: 30 },
        columns: 1
      },
      sections: defaultPDFSections.map(section => ({
        ...section,
        styling: {
          ...section.styling,
          color: section.styling.color === '#3B82F6' ? '#6B7280' : section.styling.color,
          backgroundColor: section.styling.backgroundColor?.replace('#3B82F6', '#6B7280'),
          borderLeft: section.styling.borderLeft ? { ...section.styling.borderLeft, color: '#6B7280' } : undefined
        }
      })),
      styling: {
        fontFamily: 'Arial, sans-serif',
        primaryColor: '#6B7280',
        secondaryColor: '#374151',
        accentColor: '#9CA3AF',
        backgroundColor: '#ffffff',
        headerGradient: false,
        roundedCorners: false,
        shadows: false
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    category: 'luxury',
    preview: '/templates/luxury-gold.jpg',
    colors: { primary: '#D97706', secondary: '#92400E', accent: '#FBBF24' },
    pdfTemplate: {
      id: 'pdf-luxury-gold',
      name: 'Luxury Gold PDF',
      layout: {
        pageSize: 'a4',
        orientation: 'portrait',
        margins: { top: 50, right: 50, bottom: 50, left: 50 },
        columns: 1
      },
      sections: defaultPDFSections.map(section => ({
        ...section,
        styling: {
          ...section.styling,
          color: section.styling.color === '#3B82F6' ? '#D97706' : section.styling.color,
          backgroundColor: section.styling.backgroundColor?.replace('#3B82F6', '#D97706'),
          borderLeft: section.styling.borderLeft ? { ...section.styling.borderLeft, color: '#D97706' } : undefined
        }
      })),
      styling: {
        fontFamily: 'Georgia, serif',
        primaryColor: '#D97706',
        secondaryColor: '#92400E',
        accentColor: '#FBBF24',
        backgroundColor: '#ffffff',
        headerGradient: true,
        roundedCorners: true,
        shadows: true
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  },
  {
    id: 'cozy-red',
    name: 'Cozy Red',
    category: 'cozy',
    preview: '/templates/cozy-red.jpg',
    colors: { primary: '#DC2626', secondary: '#991B1B', accent: '#F87171' },
    pdfTemplate: {
      id: 'pdf-cozy-red',
      name: 'Cozy Red PDF',
      layout: {
        pageSize: 'a4',
        orientation: 'portrait',
        margins: { top: 40, right: 40, bottom: 40, left: 40 },
        columns: 1
      },
      sections: defaultPDFSections.map(section => ({
        ...section,
        styling: {
          ...section.styling,
          color: section.styling.color === '#3B82F6' ? '#DC2626' : section.styling.color,
          backgroundColor: section.styling.backgroundColor?.replace('#3B82F6', '#DC2626'),
          borderLeft: section.styling.borderLeft ? { ...section.styling.borderLeft, color: '#DC2626' } : undefined
        }
      })),
      styling: {
        fontFamily: 'Arial, sans-serif',
        primaryColor: '#DC2626',
        secondaryColor: '#991B1B',
        accentColor: '#F87171',
        backgroundColor: '#ffffff',
        headerGradient: true,
        roundedCorners: true,
        shadows: false
      },
      createdAt: new Date(),
      updatedAt: new Date()
    }
  },
  {
    id: 'modern-purple',
    name: 'Modern Purple',
    category: 'modern',
    preview: '/templates/modern-purple.jpg',
    colors: { primary: '#7C3AED', secondary: '#5B21B6', accent: '#A78BFA' }
  },
  {
    id: 'classic-navy',
    name: 'Classic Navy',
    category: 'classic',
    preview: '/templates/classic-navy.jpg',
    colors: { primary: '#1E40AF', secondary: '#1E3A8A', accent: '#60A5FA' }
  },
  {
    id: 'minimal-black',
    name: 'Minimal Black',
    category: 'minimal',
    preview: '/templates/minimal-black.jpg',
    colors: { primary: '#111827', secondary: '#000000', accent: '#6B7280' }
  },
  {
    id: 'luxury-rose',
    name: 'Luxury Rose',
    category: 'luxury',
    preview: '/templates/luxury-rose.jpg',
    colors: { primary: '#E11D48', secondary: '#BE185D', accent: '#FB7185' }
  },
  {
    id: 'cozy-orange',
    name: 'Cozy Orange',
    category: 'cozy',
    preview: '/templates/cozy-orange.jpg',
    colors: { primary: '#EA580C', secondary: '#C2410C', accent: '#FB923C' }
  }
];