/*
  # Seed database with initial data

  1. PDF Templates
    - Insert default PDF templates with configurations
  
  2. Local Information
    - Insert sample local information for testing
  
  3. Admin User
    - Create admin user for platform management
*/

-- Insert PDF templates
INSERT INTO pdf_templates (id, name, category, colors, layout, sections, styling) VALUES
(
  'modern-blue',
  'Modern Blue',
  'modern',
  '{"primary": "#3B82F6", "secondary": "#1E40AF", "accent": "#60A5FA"}',
  '{"pageSize": "a4", "orientation": "portrait", "margins": {"top": 40, "right": 40, "bottom": 40, "left": 40}, "columns": 1}',
  '[
    {"id": "header", "type": "header", "title": "Property Header", "enabled": true, "order": 1, "content": "Welcome to {{propertyName}}", "styling": {"fontSize": 32, "fontWeight": "bold", "color": "#FFFFFF", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "property-info", "type": "property-info", "title": "Property Description", "enabled": true, "order": 2, "content": "Welcome to Your Stay", "styling": {"fontSize": 24, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#3B82F6"}}},
    {"id": "checkin", "type": "checkin", "title": "Check-in Instructions", "enabled": true, "order": 3, "content": "Check-in Instructions", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#3B82F6"}}},
    {"id": "wifi", "type": "wifi", "title": "WiFi Information", "enabled": true, "order": 4, "content": "WiFi Information", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#3B82F6", "backgroundColor": "#3B82F615", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "rules", "type": "rules", "title": "House Rules", "enabled": true, "order": 5, "content": "House Rules", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#3B82F6"}}},
    {"id": "local-info", "type": "local-info", "title": "Local Information & Recommendations", "enabled": true, "order": 6, "content": "Local Information & Recommendations", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 20, "borderLeft": {"width": 4, "color": "#3B82F6"}}},
    {"id": "emergency", "type": "emergency", "title": "Emergency Contacts", "enabled": true, "order": 7, "content": "Emergency Contacts", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#856404", "backgroundColor": "#fff3cd", "padding": 20, "marginTop": 0, "marginBottom": 30}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": true, "order": 8, "content": "Generated by RentalBook Platform", "styling": {"fontSize": 12, "fontWeight": "normal", "color": "#666666", "padding": 20, "marginTop": 20, "marginBottom": 0}}
  ]',
  '{"fontFamily": "Arial, sans-serif", "primaryColor": "#3B82F6", "secondaryColor": "#1E40AF", "accentColor": "#60A5FA", "backgroundColor": "#ffffff", "headerGradient": true, "roundedCorners": true, "shadows": true}'
),
(
  'classic-green',
  'Classic Green',
  'classic',
  '{"primary": "#059669", "secondary": "#047857", "accent": "#34D399"}',
  '{"pageSize": "a4", "orientation": "portrait", "margins": {"top": 40, "right": 40, "bottom": 40, "left": 40}, "columns": 1}',
  '[
    {"id": "header", "type": "header", "title": "Property Header", "enabled": true, "order": 1, "content": "Welcome to {{propertyName}}", "styling": {"fontSize": 32, "fontWeight": "bold", "color": "#FFFFFF", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "property-info", "type": "property-info", "title": "Property Description", "enabled": true, "order": 2, "content": "Welcome to Your Stay", "styling": {"fontSize": 24, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#059669"}}},
    {"id": "checkin", "type": "checkin", "title": "Check-in Instructions", "enabled": true, "order": 3, "content": "Check-in Instructions", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#059669"}}},
    {"id": "wifi", "type": "wifi", "title": "WiFi Information", "enabled": true, "order": 4, "content": "WiFi Information", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#059669", "backgroundColor": "#05966915", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "rules", "type": "rules", "title": "House Rules", "enabled": true, "order": 5, "content": "House Rules", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#059669"}}},
    {"id": "local-info", "type": "local-info", "title": "Local Information & Recommendations", "enabled": true, "order": 6, "content": "Local Information & Recommendations", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 20, "borderLeft": {"width": 4, "color": "#059669"}}},
    {"id": "emergency", "type": "emergency", "title": "Emergency Contacts", "enabled": true, "order": 7, "content": "Emergency Contacts", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#856404", "backgroundColor": "#fff3cd", "padding": 20, "marginTop": 0, "marginBottom": 30}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": true, "order": 8, "content": "Generated by RentalBook Platform", "styling": {"fontSize": 12, "fontWeight": "normal", "color": "#666666", "padding": 20, "marginTop": 20, "marginBottom": 0}}
  ]',
  '{"fontFamily": "Arial, sans-serif", "primaryColor": "#059669", "secondaryColor": "#047857", "accentColor": "#34D399", "backgroundColor": "#ffffff", "headerGradient": true, "roundedCorners": false, "shadows": false}'
),
(
  'minimal-gray',
  'Minimal Gray',
  'minimal',
  '{"primary": "#6B7280", "secondary": "#374151", "accent": "#9CA3AF"}',
  '{"pageSize": "a4", "orientation": "portrait", "margins": {"top": 30, "right": 30, "bottom": 30, "left": 30}, "columns": 1}',
  '[
    {"id": "header", "type": "header", "title": "Property Header", "enabled": true, "order": 1, "content": "Welcome to {{propertyName}}", "styling": {"fontSize": 32, "fontWeight": "bold", "color": "#FFFFFF", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "property-info", "type": "property-info", "title": "Property Description", "enabled": true, "order": 2, "content": "Welcome to Your Stay", "styling": {"fontSize": 24, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#6B7280"}}},
    {"id": "checkin", "type": "checkin", "title": "Check-in Instructions", "enabled": true, "order": 3, "content": "Check-in Instructions", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#6B7280"}}},
    {"id": "wifi", "type": "wifi", "title": "WiFi Information", "enabled": true, "order": 4, "content": "WiFi Information", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#6B7280", "backgroundColor": "#6B728015", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "rules", "type": "rules", "title": "House Rules", "enabled": true, "order": 5, "content": "House Rules", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#6B7280"}}},
    {"id": "local-info", "type": "local-info", "title": "Local Information & Recommendations", "enabled": true, "order": 6, "content": "Local Information & Recommendations", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 20, "borderLeft": {"width": 4, "color": "#6B7280"}}},
    {"id": "emergency", "type": "emergency", "title": "Emergency Contacts", "enabled": true, "order": 7, "content": "Emergency Contacts", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#856404", "backgroundColor": "#fff3cd", "padding": 20, "marginTop": 0, "marginBottom": 30}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": true, "order": 8, "content": "Generated by RentalBook Platform", "styling": {"fontSize": 12, "fontWeight": "normal", "color": "#666666", "padding": 20, "marginTop": 20, "marginBottom": 0}}
  ]',
  '{"fontFamily": "Arial, sans-serif", "primaryColor": "#6B7280", "secondaryColor": "#374151", "accentColor": "#9CA3AF", "backgroundColor": "#ffffff", "headerGradient": false, "roundedCorners": false, "shadows": false}'
),
(
  'luxury-gold',
  'Luxury Gold',
  'luxury',
  '{"primary": "#D97706", "secondary": "#92400E", "accent": "#FBBF24"}',
  '{"pageSize": "a4", "orientation": "portrait", "margins": {"top": 50, "right": 50, "bottom": 50, "left": 50}, "columns": 1}',
  '[
    {"id": "header", "type": "header", "title": "Property Header", "enabled": true, "order": 1, "content": "Welcome to {{propertyName}}", "styling": {"fontSize": 32, "fontWeight": "bold", "color": "#FFFFFF", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "property-info", "type": "property-info", "title": "Property Description", "enabled": true, "order": 2, "content": "Welcome to Your Stay", "styling": {"fontSize": 24, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#D97706"}}},
    {"id": "checkin", "type": "checkin", "title": "Check-in Instructions", "enabled": true, "order": 3, "content": "Check-in Instructions", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#D97706"}}},
    {"id": "wifi", "type": "wifi", "title": "WiFi Information", "enabled": true, "order": 4, "content": "WiFi Information", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#D97706", "backgroundColor": "#D9770615", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "rules", "type": "rules", "title": "House Rules", "enabled": true, "order": 5, "content": "House Rules", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#D97706"}}},
    {"id": "local-info", "type": "local-info", "title": "Local Information & Recommendations", "enabled": true, "order": 6, "content": "Local Information & Recommendations", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 20, "borderLeft": {"width": 4, "color": "#D97706"}}},
    {"id": "emergency", "type": "emergency", "title": "Emergency Contacts", "enabled": true, "order": 7, "content": "Emergency Contacts", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#856404", "backgroundColor": "#fff3cd", "padding": 20, "marginTop": 0, "marginBottom": 30}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": true, "order": 8, "content": "Generated by RentalBook Platform", "styling": {"fontSize": 12, "fontWeight": "normal", "color": "#666666", "padding": 20, "marginTop": 20, "marginBottom": 0}}
  ]',
  '{"fontFamily": "Georgia, serif", "primaryColor": "#D97706", "secondaryColor": "#92400E", "accentColor": "#FBBF24", "backgroundColor": "#ffffff", "headerGradient": true, "roundedCorners": true, "shadows": true}'
),
(
  'cozy-red',
  'Cozy Red',
  'cozy',
  '{"primary": "#DC2626", "secondary": "#991B1B", "accent": "#F87171"}',
  '{"pageSize": "a4", "orientation": "portrait", "margins": {"top": 40, "right": 40, "bottom": 40, "left": 40}, "columns": 1}',
  '[
    {"id": "header", "type": "header", "title": "Property Header", "enabled": true, "order": 1, "content": "Welcome to {{propertyName}}", "styling": {"fontSize": 32, "fontWeight": "bold", "color": "#FFFFFF", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "property-info", "type": "property-info", "title": "Property Description", "enabled": true, "order": 2, "content": "Welcome to Your Stay", "styling": {"fontSize": 24, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#DC2626"}}},
    {"id": "checkin", "type": "checkin", "title": "Check-in Instructions", "enabled": true, "order": 3, "content": "Check-in Instructions", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#DC2626"}}},
    {"id": "wifi", "type": "wifi", "title": "WiFi Information", "enabled": true, "order": 4, "content": "WiFi Information", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#DC2626", "backgroundColor": "#DC262615", "padding": 20, "marginTop": 0, "marginBottom": 20}},
    {"id": "rules", "type": "rules", "title": "House Rules", "enabled": true, "order": 5, "content": "House Rules", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 15, "borderLeft": {"width": 4, "color": "#DC2626"}}},
    {"id": "local-info", "type": "local-info", "title": "Local Information & Recommendations", "enabled": true, "order": 6, "content": "Local Information & Recommendations", "styling": {"fontSize": 20, "fontWeight": "bold", "color": "#333333", "padding": 15, "marginTop": 0, "marginBottom": 20, "borderLeft": {"width": 4, "color": "#DC2626"}}},
    {"id": "emergency", "type": "emergency", "title": "Emergency Contacts", "enabled": true, "order": 7, "content": "Emergency Contacts", "styling": {"fontSize": 18, "fontWeight": "bold", "color": "#856404", "backgroundColor": "#fff3cd", "padding": 20, "marginTop": 0, "marginBottom": 30}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": true, "order": 8, "content": "Generated by RentalBook Platform", "styling": {"fontSize": 12, "fontWeight": "normal", "color": "#666666", "padding": 20, "marginTop": 20, "marginBottom": 0}}
  ]',
  '{"fontFamily": "Arial, sans-serif", "primaryColor": "#DC2626", "secondaryColor": "#991B1B", "accentColor": "#F87171", "backgroundColor": "#ffffff", "headerGradient": true, "roundedCorners": true, "shadows": false}'
) ON CONFLICT (id) DO NOTHING;

-- Insert sample local information
INSERT INTO local_info (name, category, address, phone, description, city, country, verified, rating, opening_hours) VALUES
('City General Hospital', 'hospital', '456 Medical Center Blvd', '+1-555-0123', '24/7 emergency services', 'Santa Monica', 'USA', true, 4.2, '24/7'),
('Joe''s Pharmacy', 'pharmacy', '789 Main Street', '+1-555-0456', 'Full-service pharmacy with prescription services', 'Santa Monica', 'USA', true, 4.5, '8:00 AM - 10:00 PM'),
('Ocean Breeze Restaurant', 'restaurant', '321 Seaside Avenue', '+1-555-0789', 'Fresh seafood with ocean views', 'Santa Monica', 'USA', true, 4.8, '11:00 AM - 11:00 PM'),
('Whole Foods Market', 'supermarket', '1425 Montana Avenue', '+1-555-0321', 'Organic groceries and fresh produce', 'Santa Monica', 'USA', true, 4.3, '7:00 AM - 11:00 PM'),
('Santa Monica Pier', 'attraction', '200 Santa Monica Pier', '+1-310-458-8900', 'Famous pier with amusement park and restaurants', 'Santa Monica', 'USA', true, 4.6, '6:00 AM - 12:00 AM'),
('Venice Beach', 'beach', 'Venice Beach Boardwalk', null, 'Famous beach with boardwalk and street performers', 'Venice', 'USA', true, 4.4, '24/7'),
('Dr. Sarah Johnson', 'doctor', '1234 Wilshire Blvd, Suite 200', '+1-555-0654', 'Family medicine and urgent care', 'Santa Monica', 'USA', true, 4.7, '8:00 AM - 6:00 PM'),
('Beach Bike Rentals', 'activity', '1619 Ocean Front Walk', '+1-555-0987', 'Bike rentals for exploring the beach path', 'Santa Monica', 'USA', true, 4.1, '9:00 AM - 7:00 PM')
ON CONFLICT (id) DO NOTHING;